Regex
yury-1980/Clevertec pull request #1
Opened 2022-03-14 20:01 UTC by yury-1980

Из файла грузит только перечень товара.

2022-03-14 21:57 UTC, ZIban89 requested changes
Смотрел только регулярки, глубже не лез, код не запускал

2022-03-14 21:57 UTC, ZIban89 commented on src/main/java/ru/clevertec/fabric/Reader.java
>          String regId = "^([1-9]|[0-9]\\d|100)$";
`[0-9]\\d`
Пройдёт 07

2022-03-14 21:57 UTC, ZIban89 commented on src/main/java/ru/clevertec/fabric/Reader.java
> +        String regTitle = "^[A-ZА-Я][a-zа-я]{2,29}$";
Пройдёт Цepter и Gрибы

2022-03-14 21:57 UTC, ZIban89 commented on src/main/java/ru/clevertec/fabric/Reader.java
>          String regPrice = "^(([1-9][0-9]\\.[0-9]{2})|100.[0-9]{2})$|^([1-9]\\.[0-9]{2})$";
`100.[0-9]{2}`
Пройдёт 100.99

2022-03-15 08:47 UTC, TeamTiramisy approved these changes

2022-03-15 11:40 UTC, 4ewka approved these changes
Regex approved

2022-03-15 16:10 UTC, ZIban89 approved these changes
Смотрел только регулярки, код не запускал.

2022-03-16 20:45 UTC, gitbic approved these changes
+

2022-03-17 08:27 UTC, merged