sprin
yury-1980/Clevertec pull request #6
Opened 2022-08-23 16:57 UTC by yury-1980

2022-08-24 07:06 UTC, labanovichttps requested changes

2022-08-24 07:06 UTC, labanovichttps commented on src/main/java/ru/clevertec/SpringConfig.java
> +@PropertySource("classpath:connectionDB.properties")
properties fil'a не должно быть, заменить на yaml

2022-08-24 07:06 UTC, labanovichttps commented on src/main/java/ru/clevertec/controller/CommandType.java
>  //    private CommandType(){}
?? закомментированного кода старайся не делать

2022-08-24 07:06 UTC, labanovichttps commented on src/main/java/ru/clevertec/controller/ConvertTxt_Pdf.java
>  public class ConvertTxt_Pdf implements Convertible {
неправильно назван класс, посмотри конвенции по именованию

2022-08-24 07:06 UTC, labanovichttps commented on src/main/java/ru/clevertec/controller/impl/Purchase.java
> +        private  ConnectionDB connectionDB = ConnectionDB.getInstance();
почему это не компонент?

2022-08-24 07:06 UTC, labanovichttps commented on src/main/java/ru/clevertec/service/ProposedPurchase.java
>  public class ProposedPurchase {
если у тебя репо то ставь @Repository, если сервис, то @Service

2022-08-26 06:47 UTC, closed without merging

2022-08-26 07:38 UTC, yury-1980 commented on src/main/java/ru/clevertec/controller/ConvertTxt_Pdf.java
>  public class ConvertTxt_Pdf implements Convertible {
OK.

2022-08-26 07:38 UTC, yury-1980 commented on src/main/java/ru/clevertec/controller/impl/Purchase.java
> +        private  ConnectionDB connectionDB = ConnectionDB.getInstance();
OK.

2022-08-26 08:15 UTC, yury-1980 commented on src/main/java/ru/clevertec/service/ProposedPurchase.java
>  public class ProposedPurchase {
Ok.

2022-08-26 08:16 UTC, yury-1980 commented on src/main/java/ru/clevertec/controller/CommandType.java
>  //    private CommandType(){}
Ok.

2022-08-26 10:02 UTC, yury-1980 commented on src/main/java/ru/clevertec/SpringConfig.java
> +@PropertySource("classpath:connectionDB.properties")
Ok.

2022-08-26 10:56 UTC, yury-1980 commented on src/main/java/ru/clevertec/SpringConfig.java
> +@PropertySource("classpath:connectionDB.properties")
Заменил, но пока подключил в коде.